# Generated by Django 2.1 on 2019-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='privateKey',
            field=models.CharField(default='0', max_length=1028),
        ),
        migrations.AddField(
            model_name='profile',
            name='publickKey',
            field=models.CharField(default='0', max_length=1028),
        ),
    ]
