# Generated by Django 2.1 on 2019-04-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypt', '0002_auto_20190407_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='publickKey',
            new_name='publicKey',
        ),
    ]
